package com.oktacamerakit

class Accessory {

    static constraints = {}

    User owner               // user that is the owner
    String name              // name of the accessory, ie EN-EL14A Battery
    String category          // such as "power" or "tripods"
    Integer numberAvailable  // how many are there?

    // grails will use a human-friendly name instead of an id
    // in the scaffolding autogenerated pages
    String toString() {
        return name
    }

    static belongsTo = [camera: Camera]
}
